FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip && pip install uv
RUN uv pip install --system --no-deps .
EXPOSE 8000
ENTRYPOINT ["uv", "run"]
CMD ["uvicorn", "producer_api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
